import Foundation
import PackagePlugin

@main
struct BuildInfoPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let output = context.pluginWorkDirectory.appending(subpath: "BuildInfo.swift")
        return [
            .prebuildCommand(
                displayName: "Generate BuildInfo.swift",
                executable: .init("/bin/bash"),
                arguments: [
                    "-c",
                    """
                    REPO_ROOT="\(context.package.directory.string)/../.."
                    VERSION=$(git -C "$REPO_ROOT" describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
                    COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
                    BRANCH=$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null)
                    if [ -n "$BRANCH" ] && [ "$BRANCH" != "master" ]; then BRANCH_TAG=" [$BRANCH]"; else BRANCH_TAG=""; fi
                    if git -C "$REPO_ROOT" diff --quiet 2>/dev/null; then DIRTY=""; else DIRTY="-dirty"; fi
                    BUILD_TIME=$(date "+%Y-%m-%d %H:%M:%S")
                    cat > "\(output.string)" <<SWIFT
                    // Auto-generated by BuildInfoPlugin — do not edit
                    enum BuildInfo {
                        static let version = "$VERSION$DIRTY$BRANCH_TAG ($COMMIT) built $BUILD_TIME"
                    }
                    SWIFT
                    """,
                ],
                outputFilesDirectory: context.pluginWorkDirectory
            )
        ]
    }
}
